package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ElasticsearchService elasticsearchService;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> fileMd5}
    private final Map<String, Map<Integer, String>> sessionReferenceMappings = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      ElasticsearchService elasticsearchService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.elasticsearchService = elasticsearchService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());
            
            // 3. 执行带权限过滤的混合搜索：多召回后按 fileMd5 去重，保留得分最高的 chunk，最终只取 top 3
            List<SearchResult> rawResults = searchService.searchWithPermission(userMessage, userId, 20);
            // 每个文件只保留得分最高的 chunk，按分数降序排列，只取最匹配的 3 条
            List<SearchResult> searchResults = rawResults.stream()
                    .collect(java.util.stream.Collectors.toMap(
                            SearchResult::getFileMd5,
                            r -> r,
                            (a, b) -> (a.getScore() != null && b.getScore() != null && a.getScore() >= b.getScore()) ? a : b,
                            LinkedHashMap::new
                    ))
                    .values().stream()
                    .sorted(Comparator.comparingDouble(r -> -(r.getScore() != null ? r.getScore() : 0.0)))
                    .limit(3)
                    .collect(java.util.stream.Collectors.toList());
            logger.info("[流程] 搜索完成，原始结果数={}，取最高分3条", rawResults.size());

            // 3.5 通过 WebSocket 将检索结果推送到前端（在 DeepSeek 流式调用之前同步发送）
            sendSearchResults(session, searchResults);

            // 等待足够时间让前端收到并处理 search_results 消息，再开始流式输出
            try {
                Thread.sleep(500);
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
            }
            
            // 4. 构建上下文
            String context = buildContext(searchResults, session.getId());
            
            // 5. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history, 
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    responseBuilder.append(chunk);
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });
            
            // 6. 启动一个后台任务检查并标记响应完成
            new Thread(() -> {
                try {
                    // 等待最多30秒，给API足够的响应时间
                    Thread.sleep(3000); // 先等待3秒钟，让API有时间开始响应
                    
                    // 获取当前累积的响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    
                    // 如果响应构建器存在并且已有内容，认为响应已完成
                    if (responseBuilder != null) {
                        // 记录最后2秒的响应变化，检测是否停止增长
                        String lastResponse = responseBuilder.toString();
                        int lastLength = lastResponse.length();
                        
                        Thread.sleep(2000); // 再等待2秒
                        
                        // 再次检查是否有新内容
                        if (responseBuilder.length() == lastLength) {
                            // 没有新内容，可以认为响应已完成
                            responseFuture.complete(responseBuilder.toString());
                            logger.info("DeepSeek响应已完成，长度: {}", responseBuilder.length());
                            
                            // 发送响应完成通知
                            sendCompletionNotification(session);
                            
                            // 更新对话历史
                            String completeResponse = responseBuilder.toString();
                            updateConversationHistory(conversationId, userMessage, completeResponse);
                            
                            // 输出对话存储信息以便调试
                            String redisKey = "user:" + userId + ":current_conversation";
                            logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                            
                            // 清理会话响应构建器
                            responseBuilders.remove(session.getId());
                            responseFutures.remove(session.getId());
                            logger.info("消息处理完成，用户ID: {}", userId);
                        } else {
                            // 仍有新内容，继续等待
                            logger.debug("响应仍在继续，等待完成...");
                            // 再等待最多25秒
                            for (int i = 0; i < 5; i++) {
                                Thread.sleep(5000);
                                lastLength = responseBuilder.length();
                                // 再次检查2秒内是否有新内容
                                Thread.sleep(2000);
                                if (responseBuilder.length() == lastLength) {
                                    // 没有新内容，可以认为响应已完成
                                    responseFuture.complete(responseBuilder.toString());
                                    
                                    // 发送响应完成通知
                                    sendCompletionNotification(session);
                                    
                                    // 更新对话历史
                                    String completeResponse = responseBuilder.toString();
                                    updateConversationHistory(conversationId, userMessage, completeResponse);
                                    
                                    // 输出对话存储信息以便调试
                                    String redisKey = "user:" + userId + ":current_conversation";
                                    logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                                    
                                    // 清理会话响应构建器
                                    responseBuilders.remove(session.getId());
                                    responseFutures.remove(session.getId());
                                    logger.info("消息处理完成，用户ID: {}", userId);
                                    return;
                                }
                            }
                            
                            // 如果经过多次检查仍未完成，强制完成
                            if (!responseFuture.isDone()) {
                                responseFuture.complete(responseBuilder.toString());
                                
                                // 发送响应完成通知
                                sendCompletionNotification(session);
                                
                                // 更新对话历史
                                String completeResponse = responseBuilder.toString();
                                updateConversationHistory(conversationId, userMessage, completeResponse);
                                
                                // 输出对话存储信息以便调试
                                String redisKey = "user:" + userId + ":current_conversation";
                                logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                                
                                // 清理会话响应构建器
                                responseBuilders.remove(session.getId());
                                responseFutures.remove(session.getId());
                                logger.info("消息处理强制完成，用户ID: {}", userId);
                            }
                        }
                    } else {
                        logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", session.getId());
                        RuntimeException exception = new RuntimeException("响应构建器为空");
                        responseFuture.completeExceptionally(exception);
                        // 发送错误消息
                        handleError(session, exception);
                    }
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                }
            }).start();
            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理会话响应构建器
            responseBuilders.remove(session.getId());
            // 清理响应future
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 添加助手回复（带时间戳）
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        // 创建当前会话的引用映射
        Map<Integer, String> referenceMapping = new HashMap<>();

        final int MAX_SNIPPET_LEN = 2000; // 单段最长字符数（含相邻chunk扩展后）
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String fileMd5 = result.getFileMd5();

            // 扩展相邻 chunk：前后各取 1 个，将内容拼接后作为上下文
            String snippet = buildExpandedSnippet(result, 1);
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }

            // 格式：[1] (test1.txt | MD5:abc123def456) 文件内容...
            // 这样AI和用户都能通过MD5区分同名文件
            context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));

            // 保存引用编号到MD5的映射
            if (fileMd5 != null) {
                referenceMapping.put(i + 1, fileMd5);
                // 详细日志：记录每个引用编号的映射关系
                logger.info("引用映射: sessionId={}, 引用编号#{} 文件名={}, MD5={}",
                    sessionId, i + 1, fileLabel, fileMd5);
            }
        }

        // 保存当前会话的引用映射
        sessionReferenceMappings.put(sessionId, referenceMapping);
        logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    /**
     * 扩展命中 chunk 的上下文：从 ES 取前后相邻 chunk 并拼接，
     * 确保标题行和正文不因分片边界而分离。
     */
    private String buildExpandedSnippet(SearchResult result, int expandCount) {
        String fileMd5 = result.getFileMd5();
        int chunkId = result.getChunkId() != null ? result.getChunkId() : 0;
        if (fileMd5 == null || fileMd5.isEmpty()) {
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
        try {
            List<com.yizhaoqi.smartpai.entity.EsDocument> contextChunks =
                    elasticsearchService.getChunkContext(fileMd5, chunkId, expandCount);
            if (contextChunks == null || contextChunks.isEmpty()) {
                return result.getTextContent() != null ? result.getTextContent() : "";
            }
            StringBuilder sb = new StringBuilder();
            for (com.yizhaoqi.smartpai.entity.EsDocument chunk : contextChunks) {
                if (chunk.getTextContent() != null) {
                    if (!sb.isEmpty()) sb.append("\n");
                    sb.append(chunk.getTextContent());
                }
            }
            return sb.toString();
        } catch (Exception e) {
            logger.warn("扩展 chunk 上下文失败，fileMd5={}, chunkId={}: {}", fileMd5, chunkId, e.getMessage());
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
    }

    // 用于给每个会话的 sendMessage 加锁，Spring WebSocket session 不支持并发写
    private final Map<String, Object> sessionSendLocks = new ConcurrentHashMap<>();

    private Object getSessionLock(String sessionId) {
        return sessionSendLocks.computeIfAbsent(sessionId, k -> new Object());
    }

    private void safeSend(WebSocketSession session, String json) throws Exception {
        if (session.isOpen()) {
            session.sendMessage(new TextMessage(json));
        }
    }

    private void sendSearchResults(WebSocketSession session, List<SearchResult> searchResults) {
        try {
            List<Map<String, Object>> results = new ArrayList<>();
            for (int i = 0; i < searchResults.size(); i++) {
                SearchResult sr = searchResults.get(i);
                Map<String, Object> item = new HashMap<>();
                item.put("referenceNumber", i + 1);
                item.put("fileName", sr.getFileName() != null ? sr.getFileName() : "unknown");
                item.put("fileMd5", sr.getFileMd5());
                item.put("score", sr.getScore());
                item.put("chunkId", sr.getChunkId());
                // 完整文本内容，供弹窗查看
                item.put("fullContent", sr.getTextContent() != null ? sr.getTextContent() : "");
                // snippet 不截断，前端直接展示完整内容
                String snippet = sr.getTextContent() != null ? sr.getTextContent() : "";
                item.put("snippet", snippet);
                results.add(item);
            }
            Map<String, Object> message = new HashMap<>();
            message.put("type", "search_results");
            message.put("results", results);
            message.put("totalCount", searchResults.size());
            String json = objectMapper.writeValueAsString(message);
            logger.info("[搜索结果推送] 准备发送，会话={}, 结果数={}, JSON长度={}", session.getId(), results.size(), json.length());
            safeSend(session, json);
            logger.info("[搜索结果推送] 发送成功，会话={}, 共 {} 条", session.getId(), results.size());
        } catch (Exception e) {
            logger.error("[搜索结果推送] 发送失败，会话={}, 错误={}", session.getId(), e.getMessage(), e);
        }
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            // 注意：Reactive WebClient 的 onChunk 回调是在 reactor 线程池里调用的，
            // StandardWebSocketSession.sendMessage 底层是同步的 ConcurrentWebSocketSessionDecorator，
            // 多个 reactor 线程并发调用会抛 IllegalStateException: previous message not sent yet
            // 因此这里用 synchronized 序列化写入
            synchronized (getSessionLock(session.getId())) {
                if (session.isOpen()) {
                    session.sendMessage(new TextMessage(jsonChunk));
                }
            }
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            safeSend(session, notificationJson);
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            safeSend(session, errorJson);
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        // 设置停止标志
        stopFlags.put(sessionId, true);

        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop",
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            safeSend(session, stopJson);
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }

        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    /**
     * 清理会话的引用映射
     *
     * @param sessionId WebSocket会话ID
     */
    public void clearSessionReferenceMapping(String sessionId) {
        Map<Integer, String> removed = sessionReferenceMappings.remove(sessionId);
        if (removed != null) {
            logger.info("清理会话 {} 的引用映射，共 {} 条", sessionId, removed.size());
        }
    }
}
