package com.smart.kf.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.smart.kf.client.ModelClient;
import com.smart.kf.entity.EsDocument;
import com.smart.kf.entity.SearchResult;
import com.smart.kf.exception.CustomException;
import com.smart.kf.model.ApiKeyConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;
import reactor.core.Disposable;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CancellationException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 *
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {

    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final Duration CONVERSATION_TTL = Duration.ofDays(7);
    private static final int CHUNK_CONTEXT_EXPAND_COUNT = 1;
    private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private enum StreamTerminalState {
        ACTIVE,
        COMPLETED,
        STOPPED,
        FAILED
    }

    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final ModelClient modelClient;
    private final ElasticsearchService elasticsearchService;
    private final ApiKeyConfigService apiKeyConfigService;
    private final ObjectMapper objectMapper;

    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 用于记录每个会话当前流式响应的终态
    private final Map<String, StreamTerminalState> streamTerminalStates = new ConcurrentHashMap<>();
    // 用于存储每个会话的流式订阅，便于主动取消上游请求
    private final Map<String, Disposable> streamSubscriptions = new ConcurrentHashMap<>();
    // 用于存储每个会话的引用映射：sessionId -> {referenceNumber -> fileMd5}
    private final Map<String, Map<Integer, String>> sessionReferenceMappings = new ConcurrentHashMap<>();
    // 用于给每个会话的 sendMessage 加锁，Spring WebSocket session 不支持并发写
    private final Map<String, Object> sessionSendLocks = new ConcurrentHashMap<>();
    // 用于标记每个会话是否已经发送过错误消息，防止 completion 覆盖
    private final Map<String, AtomicBoolean> sessionErrorSent = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      ModelClient modelClient,
                      ElasticsearchService elasticsearchService,
                      ApiKeyConfigService apiKeyConfigService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.modelClient = modelClient;
        this.elasticsearchService = elasticsearchService;
        this.apiKeyConfigService = apiKeyConfigService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, String requestedConversationId, WebSocketSession session) {
        processMessage(userId, userMessage, requestedConversationId, null, session);
    }

    /**
     * 处理聊天消息，支持指定 API Key 配置 ID。
     *
     * @param apiKeyConfigId 指定要使用的 API Key 配置 ID（null 时优先使用激活配置，最终降级到 YAML 配置）
     */
    public void processMessage(String userId, String userMessage, String requestedConversationId,
                               Long apiKeyConfigId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("开始处理消息，用户ID: {}, WebSocket会话ID: {}, 目标会话ID: {}, apiKeyConfigId: {}",
                userId, sessionId, requestedConversationId, apiKeyConfigId);
        try {
            streamTerminalStates.put(sessionId, StreamTerminalState.ACTIVE);
            sessionErrorSent.put(sessionId, new AtomicBoolean(false));

            // 1. 获取或创建业务会话 ID
            String conversationId = resolveConversationId(userId, requestedConversationId);
            logger.info("业务会话ID: {}, 用户ID: {}", conversationId, userId);

            // 为当前WebSocket会话创建响应构建器
            responseBuilders.put(sessionId, new StringBuilder());
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(sessionId, responseFuture);

            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到会话 {} 的 {} 条历史对话", conversationId, history.size());

            // 3. 执行带权限过滤的混合搜索：多召回后按 fileMd5 去重，保留得分最高的 chunk，最终只取 top 3
            List<SearchResult> rawResults = searchService.searchWithPermission(userMessage, userId, 20);
            List<SearchResult> searchResults = rawResults.stream()
                    .collect(java.util.stream.Collectors.toMap(
                            SearchResult::getFileMd5,
                            r -> r,
                            (a, b) -> (a.getScore() != null && b.getScore() != null && a.getScore() >= b.getScore()) ? a : b,
                            LinkedHashMap::new
                    ))
                    .values().stream()
                    .sorted(Comparator.comparingDouble(r -> -(r.getScore() != null ? r.getScore() : 0.0)))
                    .limit(3)
                    .collect(java.util.stream.Collectors.toList());
            logger.info("[流程] 搜索完成，原始结果数={}，取最高分3条", rawResults.size());

            // 3.5 通过 WebSocket 将检索结果推送到前端（在 AI 流式调用之前同步发送）
            sendSearchResults(session, searchResults);

            try {
                Thread.sleep(500);
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
            }

            // 4. 构建上下文
            String context = buildContext(searchResults, sessionId);

            // 5. 解析要使用的 API Key 配置（指定 ID > 激活配置 > YAML 默认配置）
            ApiKeyConfig apiKeyConfig = resolveApiKeyConfig(apiKeyConfigId);

            // 6. 调用 AI API 并处理流式响应
            if (apiKeyConfig != null) {
                logger.info("调用 AI API 生成回复，使用配置：id={}, name={}, model={}，业务会话ID: {}",
                        apiKeyConfig.getId(), apiKeyConfig.getName(), apiKeyConfig.getModelName(), conversationId);
            } else {
                logger.info("调用 AI API 生成回复（使用 YAML 默认配置），业务会话ID: {}", conversationId);
            }
            Disposable streamSubscription = modelClient.streamResponse(userMessage, context, history, apiKeyConfig,
                chunk -> {
                    if (isStreamInactive(sessionId)) {
                        logger.debug("忽略非活跃会话的响应块，会话ID: {}", sessionId);
                        return;
                    }

                    StringBuilder responseBuilder = responseBuilders.get(sessionId);
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    logger.error("流式响应出错，会话ID: {}", sessionId, error);
                    handleStreamError(session, responseFuture, error, conversationId, userId, userMessage);
                },
                () -> finalizeStreamResponse(session, responseFuture, conversationId, userId, userMessage));
            streamSubscriptions.put(sessionId, streamSubscription);

        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            streamTerminalStates.remove(sessionId);
            sessionErrorSent.remove(sessionId);
            cancelStreamSubscription(sessionId);
            responseBuilders.remove(sessionId);
            CompletableFuture<String> future = responseFutures.remove(sessionId);
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    /**
     * 解析要使用的 API Key 配置：
     * 1. 若指定了 apiKeyConfigId，则查询该 ID 对应的配置
     * 2. 否则，查找当前激活的配置
     * 3. 若数据库中无任何配置，则返回 null（由 ModelClient 降级到 YAML 默认配置）
     */
    private ApiKeyConfig resolveApiKeyConfig(Long apiKeyConfigId) {
        if (apiKeyConfigId != null) {
            try {
                ApiKeyConfig config = apiKeyConfigService.getEntityById(apiKeyConfigId);
                if (config != null) {
                    return config;
                }
            } catch (Exception e) {
                logger.warn("指定的 API Key 配置 id={} 不存在，将尝试使用激活配置: {}", apiKeyConfigId, e.getMessage());
            }
        }
        return apiKeyConfigService.getActiveConfig().orElse(null);
    }

    public void ensureLegacyConversationIndex(String userId, List<String> legacyUserIds) {
        boolean hasCurrentData = !getUserConversationIds(userId).isEmpty()
                || hasText(redisTemplate.opsForValue().get(userCurrentConversationKey(userId)));
        if (hasCurrentData) {
            return;
        }

        for (String legacyUserId : legacyUserIds) {
            if (!hasText(legacyUserId)) {
                continue;
            }

            List<String> legacyConversationIds = getConversationIdsFromKey(userConversationIdsKey(legacyUserId));
            if (!legacyConversationIds.isEmpty()) {
                for (int i = legacyConversationIds.size() - 1; i >= 0; i--) {
                    attachConversationToUser(userId, legacyConversationIds.get(i));
                }
            }

            String legacyCurrentConversationId = redisTemplate.opsForValue().get(userCurrentConversationKey(legacyUserId));
            if (hasText(legacyCurrentConversationId)) {
                attachConversationToUser(userId, legacyCurrentConversationId);
            }

            if (!getUserConversationIds(userId).isEmpty()
                    || hasText(redisTemplate.opsForValue().get(userCurrentConversationKey(userId)))) {
                logger.info("已为用户 {} 迁移旧会话索引，来源用户键: {}", userId, legacyUserId);
                return;
            }
        }
    }

    public String getCurrentConversationId(String userId) {
        String currentConversationId = redisTemplate.opsForValue().get(userCurrentConversationKey(userId));
        if (hasText(currentConversationId)) {
            attachConversationToUser(userId, currentConversationId);
            return currentConversationId;
        }

        List<String> conversationIds = getUserConversationIds(userId);
        if (!conversationIds.isEmpty()) {
            currentConversationId = conversationIds.get(0);
            redisTemplate.opsForValue().set(userCurrentConversationKey(userId), currentConversationId, CONVERSATION_TTL);
            return currentConversationId;
        }

        return null;
    }

    public boolean isConversationOwnedByUser(String userId, String conversationId) {
        if (!hasText(conversationId)) {
            return false;
        }

        String currentConversationId = redisTemplate.opsForValue().get(userCurrentConversationKey(userId));
        if (conversationId.equals(currentConversationId)) {
            return true;
        }

        return getUserConversationIds(userId).contains(conversationId);
    }

    public List<Map<String, Object>> getConversationMessages(String userId, String conversationId) {
        if (!hasText(conversationId) || !isConversationOwnedByUser(userId, conversationId)) {
            return new ArrayList<>();
        }

        attachConversationToUser(userId, conversationId);
        List<Map<String, String>> history = getConversationHistory(conversationId);
        List<Map<String, Object>> messages = new ArrayList<>();
        for (Map<String, String> message : history) {
            Map<String, Object> formattedMessage = new HashMap<>();
            formattedMessage.put("role", message.get("role"));
            formattedMessage.put("content", message.get("content"));
            formattedMessage.put("timestamp", message.get("timestamp"));
            // 返回 status 和 errorMessage 字段，供前端正确渲染错误状态
            if (message.containsKey("status")) {
                formattedMessage.put("status", message.get("status"));
            }
            if (message.containsKey("errorMessage")) {
                formattedMessage.put("errorMessage", message.get("errorMessage"));
            }
            messages.add(formattedMessage);
        }
        return messages;
    }

    public List<Map<String, Object>> getConversationSessions(String userId) {
        List<String> conversationIds = getUserConversationIds(userId);
        String currentConversationId = redisTemplate.opsForValue().get(userCurrentConversationKey(userId));
        if (hasText(currentConversationId) && !conversationIds.contains(currentConversationId)) {
            conversationIds.add(0, currentConversationId);
            saveUserConversationIds(userId, conversationIds);
        }

        List<Map<String, Object>> sessions = new ArrayList<>();
        for (String conversationId : conversationIds) {
            Map<String, Object> sessionMeta = getConversationMeta(conversationId);
            if (sessionMeta.isEmpty()) {
                sessionMeta = buildConversationMetaFromHistory(userId, conversationId, getConversationHistory(conversationId));
                saveConversationMeta(conversationId, sessionMeta);
            }
            sessions.add(normalizeSessionMeta(conversationId, sessionMeta));
        }

        sessions.sort((a, b) -> String.valueOf(b.getOrDefault("updatedAt", b.getOrDefault("time", "")))
                .compareTo(String.valueOf(a.getOrDefault("updatedAt", a.getOrDefault("time", "")))));
        return sessions;
    }

    public Map<String, Object> createConversationSession(String userId) {
        String conversationId = createConversationInternal(userId);
        return normalizeSessionMeta(conversationId, getConversationMeta(conversationId));
    }

    public Map<String, Object> deleteConversationSession(String userId, String conversationId) {
        if (!hasText(conversationId) || !isConversationOwnedByUser(userId, conversationId)) {
            throw new CustomException("会话不存在或无权删除", HttpStatus.NOT_FOUND);
        }

        List<String> conversationIds = getUserConversationIds(userId);
        conversationIds.removeIf(conversationId::equals);
        saveUserConversationIds(userId, conversationIds);

        redisTemplate.delete(conversationHistoryKey(conversationId));
        redisTemplate.delete(conversationMetaKey(conversationId));

        String currentConversationId = redisTemplate.opsForValue().get(userCurrentConversationKey(userId));
        String nextConversationId = null;
        if (conversationId.equals(currentConversationId)) {
            if (!conversationIds.isEmpty()) {
                nextConversationId = conversationIds.get(0);
                redisTemplate.opsForValue().set(userCurrentConversationKey(userId), nextConversationId, CONVERSATION_TTL);
            } else {
                redisTemplate.delete(userCurrentConversationKey(userId));
            }
        } else if (hasText(currentConversationId)) {
            nextConversationId = currentConversationId;
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("deletedConversationId", conversationId);
        result.put("currentConversationId", nextConversationId == null ? "" : nextConversationId);
        result.put("remainingCount", conversationIds.size());
        return result;
    }

    public Map<String, Object> updateConversationPinned(String userId, String conversationId, boolean pinned) {
        if (!hasText(conversationId) || !isConversationOwnedByUser(userId, conversationId)) {
            throw new CustomException("会话不存在或无权操作", HttpStatus.NOT_FOUND);
        }

        Map<String, Object> sessionMeta = getConversationMeta(conversationId);
        if (sessionMeta.isEmpty()) {
            sessionMeta = buildConversationMetaFromHistory(userId, conversationId, getConversationHistory(conversationId));
        }

        String pinnedAt = pinned ? currentTimestamp() : "";
        sessionMeta.put("isPinned", pinned);
        sessionMeta.put("pinnedAt", pinnedAt);
        saveConversationMeta(conversationId, sessionMeta);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("conversationId", conversationId);
        result.put("isPinned", pinned);
        result.put("pinnedAt", pinnedAt);
        return result;
    }

    private String resolveConversationId(String userId, String requestedConversationId) {
        if (hasText(requestedConversationId)) {
            if (isConversationOwnedByUser(userId, requestedConversationId)) {
                attachConversationToUser(userId, requestedConversationId);
                return requestedConversationId;
            }
            logger.warn("用户 {} 尝试访问不属于自己的会话 {}，将回退到当前会话", userId, requestedConversationId);
        }

        String currentConversationId = getCurrentConversationId(userId);
        if (hasText(currentConversationId)) {
            return currentConversationId;
        }

        return createConversationInternal(userId);
    }

    private String createConversationInternal(String userId) {
        String conversationId = UUID.randomUUID().toString();
        String now = currentTimestamp();

        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("id", conversationId);
        meta.put("userId", userId);
        meta.put("title", "新会话");
        meta.put("lastMessage", "");
        meta.put("lastRole", "");
        meta.put("time", now);
        meta.put("messageCount", 0);
        meta.put("createdAt", now);
        meta.put("updatedAt", now);
        meta.put("isPinned", false);
        meta.put("pinnedAt", "");

        saveConversationMeta(conversationId, meta);
        attachConversationToUser(userId, conversationId);
        logger.info("为用户 {} 创建新的业务会话ID: {}", userId, conversationId);
        return conversationId;
    }

    private void attachConversationToUser(String userId, String conversationId) {
        if (!hasText(userId) || !hasText(conversationId)) {
            return;
        }

        List<String> conversationIds = getUserConversationIds(userId);
        conversationIds.removeIf(conversationId::equals);
        conversationIds.add(0, conversationId);
        saveUserConversationIds(userId, conversationIds);
        redisTemplate.opsForValue().set(userCurrentConversationKey(userId), conversationId, CONVERSATION_TTL);

        Map<String, Object> sessionMeta = getConversationMeta(conversationId);
        if (sessionMeta.isEmpty()) {
            saveConversationMeta(conversationId, buildConversationMetaFromHistory(userId, conversationId, getConversationHistory(conversationId)));
        } else {
            redisTemplate.expire(conversationMetaKey(conversationId), CONVERSATION_TTL);
        }
        redisTemplate.expire(conversationHistoryKey(conversationId), CONVERSATION_TTL);
    }

    private List<String> getUserConversationIds(String userId) {
        return getConversationIdsFromKey(userConversationIdsKey(userId));
    }

    private List<String> getConversationIdsFromKey(String key) {
        String json = redisTemplate.opsForValue().get(key);
        if (!hasText(json)) {
            return new ArrayList<>();
        }

        try {
            return objectMapper.readValue(json, new TypeReference<>() {
            });
        } catch (JsonProcessingException e) {
            logger.error("解析会话索引失败: {}, key={}", e.getMessage(), key, e);
            return new ArrayList<>();
        }
    }

    private void saveUserConversationIds(String userId, List<String> conversationIds) {
        try {
            String json = objectMapper.writeValueAsString(conversationIds);
            redisTemplate.opsForValue().set(userConversationIdsKey(userId), json, CONVERSATION_TTL);
        } catch (JsonProcessingException e) {
            logger.error("序列化会话索引失败: {}, userId={}", e.getMessage(), userId, e);
        }
    }

    private Map<String, Object> getConversationMeta(String conversationId) {
        String json = redisTemplate.opsForValue().get(conversationMetaKey(conversationId));
        if (!hasText(json)) {
            return new LinkedHashMap<>();
        }

        try {
            return objectMapper.readValue(json, new TypeReference<>() {
            });
        } catch (JsonProcessingException e) {
            logger.error("解析会话元数据失败: {}, conversationId={}", e.getMessage(), conversationId, e);
            return new LinkedHashMap<>();
        }
    }

    private void saveConversationMeta(String conversationId, Map<String, Object> sessionMeta) {
        try {
            String json = objectMapper.writeValueAsString(sessionMeta);
            redisTemplate.opsForValue().set(conversationMetaKey(conversationId), json, CONVERSATION_TTL);
        } catch (JsonProcessingException e) {
            logger.error("序列化会话元数据失败: {}, conversationId={}", e.getMessage(), conversationId, e);
        }
    }

    private Map<String, Object> buildConversationMetaFromHistory(String userId, String conversationId, List<Map<String, String>> history) {
        String now = currentTimestamp();
        String title = "新会话";
        String lastMessage = "";
        String lastRole = "";
        String createdAt = now;
        String updatedAt = now;

        if (!history.isEmpty()) {
            String firstTimestamp = history.get(0).get("timestamp");
            createdAt = hasText(firstTimestamp) ? firstTimestamp : now;

            for (Map<String, String> message : history) {
                if ("user".equals(message.get("role")) && hasText(message.get("content"))) {
                    title = truncate(message.get("content"), 30);
                    break;
                }
            }

            Map<String, String> lastHistoryMessage = history.get(history.size() - 1);
            lastMessage = truncate(lastHistoryMessage.getOrDefault("content", ""), 50);
            lastRole = lastHistoryMessage.getOrDefault("role", "");
            String lastTimestamp = lastHistoryMessage.get("timestamp");
            updatedAt = hasText(lastTimestamp) ? lastTimestamp : now;
        }

        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("id", conversationId);
        meta.put("userId", userId);
        meta.put("title", title);
        meta.put("lastMessage", lastMessage);
        meta.put("lastRole", lastRole);
        meta.put("time", updatedAt);
        meta.put("messageCount", history.size());
        meta.put("createdAt", createdAt);
        meta.put("updatedAt", updatedAt);
        meta.put("isPinned", false);
        meta.put("pinnedAt", "");
        return meta;
    }

    private Map<String, Object> normalizeSessionMeta(String conversationId, Map<String, Object> meta) {
        Map<String, Object> normalized = new LinkedHashMap<>();
        normalized.put("id", conversationId);
        normalized.put("title", toStringValue(meta.get("title"), "新会话"));
        normalized.put("lastMessage", toStringValue(meta.get("lastMessage"), ""));
        normalized.put("lastRole", toStringValue(meta.get("lastRole"), ""));
        normalized.put("time", toStringValue(meta.get("time"), toStringValue(meta.get("updatedAt"), "")));
        normalized.put("messageCount", toIntValue(meta.get("messageCount")));
        normalized.put("createdAt", toStringValue(meta.get("createdAt"), ""));
        normalized.put("updatedAt", toStringValue(meta.get("updatedAt"), toStringValue(meta.get("time"), "")));
        normalized.put("isPinned", toBooleanValue(meta.get("isPinned")));
        normalized.put("pinnedAt", toStringValue(meta.get("pinnedAt"), ""));
        return normalized;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = conversationHistoryKey(conversationId);
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (!hasText(json)) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }

            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<>() {
            });
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    /**
     * 发生错误时保存消息历史，assistant 消息携带 status=error 和 errorMessage 字段
     */
    private void saveErrorMessage(String conversationId, String userId, String userMessage, String errorMessage) {
        String key = conversationHistoryKey(conversationId);
        List<Map<String, String>> history = getConversationHistory(conversationId);

        String currentTimestamp = currentTimestamp();

        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);

        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", "");
        assistantMsgMap.put("status", "error");
        assistantMsgMap.put("errorMessage", errorMessage);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);

        if (history.size() > 20) {
            history = new ArrayList<>(history.subList(history.size() - 20, history.size()));
        }

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, CONVERSATION_TTL);
            saveConversationMeta(conversationId, buildConversationMetaFromHistory(userId, conversationId, history));
            attachConversationToUser(userId, conversationId);
            logger.info("已保存错误消息到会话历史，会话ID: {}", conversationId);
        } catch (JsonProcessingException e) {
            logger.error("序列化错误消息历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private void updateConversationHistory(String conversationId, String userId, String userMessage, String response) {
        String key = conversationHistoryKey(conversationId);
        List<Map<String, String>> history = getConversationHistory(conversationId);

        String currentTimestamp = currentTimestamp();

        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);

        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);

        if (history.size() > 20) {
            history = new ArrayList<>(history.subList(history.size() - 20, history.size()));
        }

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, CONVERSATION_TTL);
            saveConversationMeta(conversationId, buildConversationMetaFromHistory(userId, conversationId, history));
            attachConversationToUser(userId, conversationId);
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        if (searchResults == null || searchResults.isEmpty()) {
            return "";
        }

        Map<Integer, String> referenceMapping = new HashMap<>();

        final int MAX_SNIPPET_LEN = 2000;
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String fileMd5 = result.getFileMd5();

            String snippet = buildExpandedSnippet(result);
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }

            context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));

            if (fileMd5 != null) {
                referenceMapping.put(i + 1, fileMd5);
                logger.info("引用映射: sessionId={}, 引用编号#{} 文件名={}, MD5={}",
                    sessionId, i + 1, fileLabel, fileMd5);
            }
        }

        sessionReferenceMappings.put(sessionId, referenceMapping);
        logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    /**
     * 扩展命中 chunk 的上下文：从 ES 取前后相邻 chunk 并拼接，
     * 确保标题行和正文不因分片边界而分离。
     */
    private String buildExpandedSnippet(SearchResult result) {
        String fileMd5 = result.getFileMd5();
        int chunkId = result.getChunkId() != null ? result.getChunkId() : 0;
        if (fileMd5 == null || fileMd5.isEmpty()) {
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
        try {
            List<EsDocument> contextChunks =
                    elasticsearchService.getChunkContext(fileMd5, chunkId, CHUNK_CONTEXT_EXPAND_COUNT);
            if (contextChunks == null || contextChunks.isEmpty()) {
                return result.getTextContent() != null ? result.getTextContent() : "";
            }
            StringBuilder sb = new StringBuilder();
            for (EsDocument chunk : contextChunks) {
                if (chunk.getTextContent() != null) {
                    if (!sb.isEmpty()) {
                        sb.append("\n");
                    }
                    sb.append(chunk.getTextContent());
                }
            }
            return sb.toString();
        } catch (Exception e) {
            logger.warn("扩展 chunk 上下文失败，fileMd5={}, chunkId={}: {}", fileMd5, chunkId, e.getMessage());
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
    }

    private boolean isStreamInactive(String sessionId) {
        return streamTerminalStates.getOrDefault(sessionId, StreamTerminalState.ACTIVE) != StreamTerminalState.ACTIVE;
    }

    private String consumeResponseContent(String sessionId) {
        StringBuilder responseBuilder = responseBuilders.remove(sessionId);
        return responseBuilder == null ? "" : responseBuilder.toString();
    }

    private void completeResponseFuture(String sessionId, CompletableFuture<String> responseFuture, String content) {
        responseFutures.remove(sessionId);
        if (responseFuture != null && !responseFuture.isDone()) {
            responseFuture.complete(content);
        }
    }

    private void completeResponseFutureExceptionally(String sessionId,
                                                     CompletableFuture<String> responseFuture,
                                                     Throwable error) {
        responseFutures.remove(sessionId);
        if (responseFuture != null && !responseFuture.isDone()) {
            responseFuture.completeExceptionally(error);
        }
    }

    private Object getSessionLock(String sessionId) {
        return sessionSendLocks.computeIfAbsent(sessionId, k -> new Object());
    }

    private void safeSend(WebSocketSession session, String json) throws Exception {
        synchronized (getSessionLock(session.getId())) {
            if (session.isOpen()) {
                session.sendMessage(new TextMessage(json));
            }
        }
    }

    private void sendSearchResults(WebSocketSession session, List<SearchResult> searchResults) {
        try {
            List<Map<String, Object>> results = new ArrayList<>();
            for (int i = 0; i < searchResults.size(); i++) {
                SearchResult sr = searchResults.get(i);
                Map<String, Object> item = new HashMap<>();
                item.put("referenceNumber", i + 1);
                item.put("fileName", sr.getFileName() != null ? sr.getFileName() : "unknown");
                item.put("fileMd5", sr.getFileMd5());
                item.put("score", sr.getScore());
                item.put("chunkId", sr.getChunkId());
                item.put("fullContent", sr.getTextContent() != null ? sr.getTextContent() : "");
                String snippet = sr.getTextContent() != null ? sr.getTextContent() : "";
                item.put("snippet", snippet);
                results.add(item);
            }
            Map<String, Object> message = new HashMap<>();
            message.put("type", "search_results");
            message.put("results", results);
            message.put("totalCount", searchResults.size());
            String json = objectMapper.writeValueAsString(message);
            logger.info("[搜索结果推送] 准备发送，会话={}, 结果数={}, JSON长度={}", session.getId(), results.size(), json.length());
            safeSend(session, json);
            logger.info("[搜索结果推送] 发送成功，会话={}, 共 {} 条", session.getId(), results.size());
        } catch (Exception e) {
            logger.error("[搜索结果推送] 发送失败，会话={}, 错误={}", session.getId(), e.getMessage(), e);
        }
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            if (isStreamInactive(session.getId())) {
                logger.debug("检测到非活跃终态，跳过发送响应块");
                return;
            }

            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            safeSend(session, jsonChunk);
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session, String status, String message) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", status,
                "message", message,
                "timestamp", currentTime,
                "date", LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            safeSend(session, notificationJson);
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        String sessionId = session.getId();
        AtomicBoolean errorSent = sessionErrorSent.get(sessionId);
        if (errorSent != null && errorSent.compareAndSet(false, true)) {
            try {
                String message = error.getMessage();
                if (message == null || message.isEmpty()) {
                    message = "AI服务暂时不可用，请稍后重试";
                }
                Map<String, String> errorResponse = Map.of("error", "true", "message", message);
                String errorJson = objectMapper.writeValueAsString(errorResponse);
                logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
                safeSend(session, errorJson);
                logger.error("已发送错误消息到会话: {}", session.getId());
            } catch (Exception e) {
                logger.error("发送错误消息失败: {}", e.getMessage(), e);
            }
        } else {
            logger.info("会话 {} 的错误消息已发送过，跳过重复发送", sessionId);
        }
    }

    private void cancelStreamSubscription(String sessionId) {
        Disposable subscription = streamSubscriptions.remove(sessionId);
        if (subscription != null && !subscription.isDisposed()) {
            subscription.dispose();
            logger.info("已取消会话 {} 的上游流式订阅", sessionId);
        }
    }

    private void handleStreamError(WebSocketSession session,
                                   CompletableFuture<String> responseFuture,
                                   Throwable error) {
        handleStreamError(session, responseFuture, error, null, null, null);
    }

    private void handleStreamError(WebSocketSession session,
                                   CompletableFuture<String> responseFuture,
                                   Throwable error,
                                   String conversationId,
                                   String userId,
                                   String userMessage) {
        String sessionId = session.getId();
        StreamTerminalState terminalState = streamTerminalStates.get(sessionId);
        if (terminalState == StreamTerminalState.STOPPED) {
            logger.info("会话 {} 的流式响应已被用户中止，忽略后续异常回调: {}", sessionId, error.getMessage());
            return;
        }

        streamTerminalStates.put(sessionId, StreamTerminalState.FAILED);
        handleError(session, error);
        // 持久化错误消息，以便刷新后仍可展示
        String failedMessage = error.getMessage() != null ? error.getMessage() : "响应处理失败";
        if (conversationId != null && userId != null && userMessage != null) {
            saveErrorMessage(conversationId, userId, userMessage, failedMessage);
        }
        // 延迟发送 completion failed，确保 error 消息先到达前端
        CompletableFuture.delayedExecutor(500, java.util.concurrent.TimeUnit.MILLISECONDS)
                .execute(() -> {
                    try {
                        if (session.isOpen()) {
                            sendCompletionNotification(session, "failed", failedMessage);
                        }
                    } catch (Exception e) {
                        logger.warn("延迟发送 completion failed 通知失败: {}", e.getMessage());
                    }
                });
        completeResponseFutureExceptionally(sessionId, responseFuture, error);
        cancelStreamSubscription(sessionId);
        responseBuilders.remove(sessionId);
        streamTerminalStates.remove(sessionId);
        sessionErrorSent.remove(sessionId);
        logger.warn("流式响应异常结束，会话ID: {}", sessionId, error);
    }

    private void finalizeStreamResponse(WebSocketSession session,
                                        CompletableFuture<String> responseFuture,
                                        String conversationId,
                                        String userId,
                                        String userMessage) {
        String sessionId = session.getId();
        StreamTerminalState terminalState = streamTerminalStates.get(sessionId);
        if (terminalState == StreamTerminalState.STOPPED) {
            logger.info("会话 {} 的流式响应已停止，忽略完成回调", sessionId);
            return;
        }
        if (terminalState == StreamTerminalState.FAILED) {
            logger.info("会话 {} 的流式响应已失败，忽略完成回调", sessionId);
            return;
        }

        streamTerminalStates.put(sessionId, StreamTerminalState.COMPLETED);
        String completeResponse = consumeResponseContent(sessionId);

        logger.info("DeepSeek响应已完成，长度: {}，会话ID: {}", completeResponse.length(), sessionId);
        cancelStreamSubscription(sessionId);
        completeResponseFuture(sessionId, responseFuture, completeResponse);
        sendCompletionNotification(session, "finished", "响应已完成");
        updateConversationHistory(conversationId, userId, userMessage, completeResponse);

        String redisKey = userCurrentConversationKey(userId);
        logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);

        streamTerminalStates.remove(sessionId);
        sessionErrorSent.remove(sessionId);
        logger.info("消息处理完成，用户ID: {}，会话ID: {}", userId, sessionId);
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        StreamTerminalState terminalState = streamTerminalStates.get(sessionId);
        if (terminalState != null && terminalState != StreamTerminalState.ACTIVE) {
            logger.info("会话 {} 当前终态为 {}，跳过重复停止", sessionId, terminalState);
            return;
        }

        streamTerminalStates.put(sessionId, StreamTerminalState.STOPPED);
        cancelStreamSubscription(sessionId);
        String partialResponse = consumeResponseContent(sessionId);
        CompletableFuture<String> responseFuture = responseFutures.get(sessionId);
        completeResponseFuture(sessionId, responseFuture, partialResponse);

        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = new LinkedHashMap<>();
            response.put("type", "stop");
            response.put("message", "响应已停止");
            response.put("status", "stopped");
            response.put("partialContent", partialResponse);
            response.put("timestamp", currentTime);
            response.put("date", java.time.Instant.ofEpochMilli(currentTime).toString());
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            safeSend(session, stopJson);
            sendCompletionNotification(session, "stopped", "响应已停止");
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        } finally {
            streamTerminalStates.remove(sessionId);
        }
    }

    public void clearSessionState(String sessionId) {
        Map<Integer, String> removedReferences = sessionReferenceMappings.remove(sessionId);
        String partialResponse = consumeResponseContent(sessionId);
        CompletableFuture<String> removedFuture = responseFutures.get(sessionId);
        StreamTerminalState removedTerminalState = streamTerminalStates.remove(sessionId);
        Disposable removedSubscription = streamSubscriptions.remove(sessionId);
        Object removedLock = sessionSendLocks.remove(sessionId);

        if (removedSubscription != null && !removedSubscription.isDisposed()) {
            removedSubscription.dispose();
        }

        if (removedFuture != null && !removedFuture.isDone()) {
            completeResponseFutureExceptionally(
                    sessionId,
                    removedFuture,
                    new CancellationException("WebSocket session closed: " + sessionId)
            );
        }

        logger.info(
                "清理会话状态完成，sessionId={}, referencesRemoved={}, responseLength={}, futureRemoved={}, terminalState={}, subscriptionRemoved={}, lockRemoved={}",
                sessionId,
                removedReferences != null ? removedReferences.size() : 0,
                partialResponse.length(),
                removedFuture != null,
                removedTerminalState,
                removedSubscription != null,
                removedLock != null
        );
    }

    private String conversationHistoryKey(String conversationId) {
        return "conversation:" + conversationId;
    }

    private String conversationMetaKey(String conversationId) {
        return "conversation:" + conversationId + ":meta";
    }

    private String userConversationIdsKey(String userId) {
        return "user:" + userId + ":conversation_ids";
    }

    private String userCurrentConversationKey(String userId) {
        return "user:" + userId + ":current_conversation";
    }

    private String currentTimestamp() {
        return LocalDateTime.now().format(TIMESTAMP_FORMATTER);
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }

    private String truncate(String value, int maxLength) {
        if (!hasText(value)) {
            return "";
        }
        return value.length() > maxLength ? value.substring(0, maxLength) + "..." : value;
    }

    private String toStringValue(Object value, String defaultValue) {
        return value == null ? defaultValue : String.valueOf(value);
    }

    private int toIntValue(Object value) {
        if (value instanceof Number number) {
            return number.intValue();
        }
        if (value instanceof String text) {
            try {
                return Integer.parseInt(text);
            } catch (NumberFormatException e) {
                logger.warn("会话消息数格式非法: {}", text);
            }
        }
        return 0;
    }

    private boolean toBooleanValue(Object value) {
        if (value instanceof Boolean bool) {
            return bool;
        }
        if (value instanceof String text) {
            return Boolean.parseBoolean(text);
        }
        return false;
    }
}
