package com.smart.kf.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smart.kf.client.ModelClient;
import com.smart.kf.entity.EsDocument;
import com.smart.kf.entity.SearchResult;
import com.smart.kf.model.ApiKeyConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;
import reactor.core.Disposable;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 *
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {

    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private static final int CHUNK_CONTEXT_EXPAND_COUNT = 1;

    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final ModelClient modelClient;
    private final ElasticsearchService elasticsearchService;
    private final ApiKeyConfigService apiKeyConfigService;
    private final ConversationService conversationService;
    private final ChatSessionStateStore stateStore;
    private final ConversationHistoryService historyService;
    private final ObjectMapper objectMapper;

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      ModelClient modelClient,
                      ElasticsearchService elasticsearchService,
                      ApiKeyConfigService apiKeyConfigService,
                      ConversationService conversationService,
                      ChatSessionStateStore stateStore,
                      ConversationHistoryService historyService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.modelClient = modelClient;
        this.elasticsearchService = elasticsearchService;
        this.apiKeyConfigService = apiKeyConfigService;
        this.conversationService = conversationService;
        this.stateStore = stateStore;
        this.historyService = historyService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, String requestedConversationId, WebSocketSession session) {
        processMessage(userId, userMessage, requestedConversationId, null, session);
    }

    /**
     * 处理聊天消息，支持指定 API Key 配置 ID。
     *
     * @param apiKeyConfigId 指定要使用的 API Key 配置 ID（null 时优先使用激活配置，最终降级到 YAML 配置）
     */
    public void processMessage(String userId, String userMessage, String requestedConversationId,
                               Long apiKeyConfigId, WebSocketSession session) {
        String sessionId = session.getId();
        long requestStartNanos = System.nanoTime();
        logger.info("开始处理消息，用户ID: {}, WebSocket会话ID: {}, 目标会话ID: {}, apiKeyConfigId: {}",
                userId, sessionId, requestedConversationId, apiKeyConfigId);
        try {
            stateStore.initSession(sessionId);

            // 1. 获取或创建业务会话 ID
            String conversationId = historyService.resolveConversationId(userId, requestedConversationId);
            logger.info("业务会话ID: {}, 用户ID: {}", conversationId, userId);

            // 为当前WebSocket会话创建响应构建器
            stateStore.registerFuture(sessionId);

            // 2. 获取对话历史
            List<Map<String, String>> history = historyService.getConversationHistory(conversationId);
            logger.debug("获取到会话 {} 的 {} 条历史对话", conversationId, history.size());

            // 3. 执行带权限过滤的混合搜索：多召回后按 fileMd5 去重，保留得分最高的 chunk，最终只取 top 3
            List<SearchResult> rawResults = searchService.searchWithPermission(userMessage, userId, 20);
            List<SearchResult> searchResults = rawResults.stream()
                    .collect(java.util.stream.Collectors.toMap(
                            SearchResult::getFileMd5,
                            r -> r,
                            (a, b) -> (a.getScore() != null && b.getScore() != null && a.getScore() >= b.getScore()) ? a : b,
                            LinkedHashMap::new
                    ))
                    .values().stream()
                    .sorted(Comparator.comparingDouble(r -> -(r.getScore() != null ? r.getScore() : 0.0)))
                    .limit(3)
                    .collect(java.util.stream.Collectors.toList());
            logger.info("[流程] 搜索完成，原始结果数={}，取最高分3条", rawResults.size());
            recordQuestionAnalytics(userMessage, !searchResults.isEmpty());

            // 3.5 通过 WebSocket 将检索结果推送到前端（在 AI 流式调用之前同步发送）
            sendSearchResults(session, searchResults);

            // 4. 构建上下文
            String context = buildContext(searchResults, sessionId);

            // 5. 解析要使用的 API Key 配置（指定 ID > 激活配置 > YAML 默认配置）
            ApiKeyConfig apiKeyConfig = resolveApiKeyConfig(apiKeyConfigId);

            // 6. 调用 AI API 并处理流式响应
            if (apiKeyConfig != null) {
                logger.info("调用 AI API 生成回复，使用配置：id={}, name={}, model={}，业务会话ID: {}",
                        apiKeyConfig.getId(), apiKeyConfig.getName(), apiKeyConfig.getModelName(), conversationId);
            } else {
                logger.info("调用 AI API 生成回复（使用 YAML 默认配置），业务会话ID: {}", conversationId);
            }
            Disposable streamSubscription = modelClient.streamResponse(userMessage, context, history, apiKeyConfig,
                chunk -> {
                    if (stateStore.isInactive(sessionId)) {
                        logger.debug("忽略非活跃会话的响应块，会话ID: {}", sessionId);
                        return;
                    }

                    stateStore.appendChunk(sessionId, chunk);
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    logger.error("流式响应出错，会话ID: {}", sessionId, error);
                    handleStreamError(session, error, conversationId, userId, userMessage, requestStartNanos);
                },
                () -> finalizeStreamResponse(session, conversationId, userId, userMessage, requestStartNanos));
            stateStore.recordSubscription(sessionId, streamSubscription);

        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            stateStore.clearState(sessionId);
            stateStore.clearErrorSent(sessionId);
            cancelStreamSubscription(sessionId);
            stateStore.consumeResponse(sessionId);
            recordResponseTime(requestStartNanos);
            stateStore.completeFutureExceptionally(sessionId, e);
        }
    }

    /**
     * 解析要使用的 API Key 配置：
     * 1. 若指定了 apiKeyConfigId，则查询该 ID 对应的配置
     * 2. 否则，查找当前激活的配置
     * 3. 若数据库中无任何配置，则返回 null（由 ModelClient 降级到 YAML 默认配置）
     */
    private ApiKeyConfig resolveApiKeyConfig(Long apiKeyConfigId) {
        if (apiKeyConfigId != null) {
            try {
                ApiKeyConfig config = apiKeyConfigService.getEntityById(apiKeyConfigId);
                if (config != null) {
                    return config;
                }
            } catch (Exception e) {
                logger.warn("指定的 API Key 配置 id={} 不存在，将尝试使用激活配置: {}", apiKeyConfigId, e.getMessage());
            }
        }
        return apiKeyConfigService.getActiveConfig().orElse(null);
    }

    public void ensureLegacyConversationIndex(String userId, List<String> legacyUserIds) {
        historyService.ensureLegacyConversationIndex(userId, legacyUserIds);
    }

    public String getCurrentConversationId(String userId) {
        return historyService.getCurrentConversationId(userId);
    }

    public boolean isConversationOwnedByUser(String userId, String conversationId) {
        return historyService.isConversationOwnedByUser(userId, conversationId);
    }

    public List<Map<String, Object>> getConversationMessages(String userId, String conversationId) {
        return historyService.getConversationMessages(userId, conversationId);
    }

    public List<Map<String, Object>> getConversationSessions(String userId, String sessionType, String targetType, String targetId) {
        return historyService.getConversationSessions(userId, sessionType, targetType, targetId);
    }

    public Map<String, Object> createConversationSession(String userId, Map<String, Object> metadata) {
        return historyService.createConversationSession(userId, metadata);
    }

    public Map<String, Object> getConversationSessionMeta(String userId, String conversationId) {
        return historyService.getConversationSessionMeta(userId, conversationId);
    }

    public void appendConversationTurn(String userId, String conversationId, String userMessage, String response) {
        historyService.appendConversationTurn(userId, conversationId, userMessage, response);
    }

    public void appendConversationError(String userId, String conversationId, String userMessage, String errorMessage) {
        historyService.appendConversationError(userId, conversationId, userMessage, errorMessage);
    }

    public void truncateConversationHistory(String userId, String conversationId, int keepCount) {
        historyService.truncateConversationHistory(userId, conversationId, keepCount);
    }

    public Map<String, Object> deleteConversationSession(String userId, String conversationId) {
        return historyService.deleteConversationSession(userId, conversationId);
    }

    public Map<String, Object> updateConversationPinned(String userId, String conversationId, boolean pinned) {
        return historyService.updateConversationPinned(userId, conversationId, pinned);
    }


    private String buildContext(List<SearchResult> searchResults, String sessionId) {
        if (searchResults == null || searchResults.isEmpty()) {
            return "";
        }

        Map<Integer, String> referenceMapping = new HashMap<>();

        final int MAX_SNIPPET_LEN = 2000;
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            String fileMd5 = result.getFileMd5();

            String snippet = buildExpandedSnippet(result);
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }

            context.append(String.format("[%d] (%s | MD5:%s) %s\n", i + 1, fileLabel, fileMd5, snippet));

            if (fileMd5 != null) {
                referenceMapping.put(i + 1, fileMd5);
                logger.info("引用映射: sessionId={}, 引用编号#{} 文件名={}, MD5={}",
                    sessionId, i + 1, fileLabel, fileMd5);
            }
        }

        stateStore.recordReference(sessionId, referenceMapping);
        logger.info("保存会话 {} 的引用映射，共 {} 条: {}", sessionId, referenceMapping.size(), referenceMapping);

        return context.toString();
    }

    /**
     * 扩展命中 chunk 的上下文：从 ES 取前后相邻 chunk 并拼接，
     * 确保标题行和正文不因分片边界而分离。
     */
    private String buildExpandedSnippet(SearchResult result) {
        String fileMd5 = result.getFileMd5();
        int chunkId = result.getChunkId() != null ? result.getChunkId() : 0;
        if (fileMd5 == null || fileMd5.isEmpty()) {
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
        try {
            List<EsDocument> contextChunks =
                    elasticsearchService.getChunkContext(fileMd5, chunkId, CHUNK_CONTEXT_EXPAND_COUNT);
            if (contextChunks == null || contextChunks.isEmpty()) {
                return result.getTextContent() != null ? result.getTextContent() : "";
            }
            StringBuilder sb = new StringBuilder();
            for (EsDocument chunk : contextChunks) {
                if (chunk.getTextContent() != null) {
                    if (!sb.isEmpty()) {
                        sb.append("\n");
                    }
                    sb.append(chunk.getTextContent());
                }
            }
            return sb.toString();
        } catch (Exception e) {
            logger.warn("扩展 chunk 上下文失败，fileMd5={}, chunkId={}: {}", fileMd5, chunkId, e.getMessage());
            return result.getTextContent() != null ? result.getTextContent() : "";
        }
    }

    private void safeSend(WebSocketSession session, String json) throws Exception {
        synchronized (stateStore.getLock(session.getId())) {
            if (session.isOpen()) {
                session.sendMessage(new TextMessage(json));
            }
        }
    }

    private void sendSearchResults(WebSocketSession session, List<SearchResult> searchResults) {
        try {
            List<Map<String, Object>> results = new ArrayList<>();
            for (int i = 0; i < searchResults.size(); i++) {
                SearchResult sr = searchResults.get(i);
                Map<String, Object> item = new HashMap<>();
                item.put("referenceNumber", i + 1);
                item.put("fileName", sr.getFileName() != null ? sr.getFileName() : "unknown");
                item.put("fileMd5", sr.getFileMd5());
                item.put("score", sr.getScore());
                item.put("chunkId", sr.getChunkId());
                item.put("fullContent", sr.getTextContent() != null ? sr.getTextContent() : "");
                String snippet = sr.getTextContent() != null ? sr.getTextContent() : "";
                item.put("snippet", snippet);
                results.add(item);
            }
            Map<String, Object> message = new HashMap<>();
            message.put("type", "search_results");
            message.put("results", results);
            message.put("totalCount", searchResults.size());
            String json = objectMapper.writeValueAsString(message);
            logger.info("[搜索结果推送] 准备发送，会话={}, 结果数={}, JSON长度={}", session.getId(), results.size(), json.length());
            safeSend(session, json);
            logger.info("[搜索结果推送] 发送成功，会话={}, 共 {} 条", session.getId(), results.size());
        } catch (Exception e) {
            logger.error("[搜索结果推送] 发送失败，会话={}, 错误={}", session.getId(), e.getMessage(), e);
        }
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            if (stateStore.isInactive(session.getId())) {
                logger.debug("检测到非活跃终态，跳过发送响应块");
                return;
            }

            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            safeSend(session, jsonChunk);
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session, String status, String message) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", status,
                "message", message,
                "timestamp", currentTime,
                "date", LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            safeSend(session, notificationJson);
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        String sessionId = session.getId();
        if (stateStore.markErrorSent(sessionId)) {
            try {
                String message = error.getMessage();
                if (message == null || message.isEmpty()) {
                    message = "AI服务暂时不可用，请稍后重试";
                }
                Map<String, String> errorResponse = Map.of("error", "true", "message", message);
                String errorJson = objectMapper.writeValueAsString(errorResponse);
                logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
                safeSend(session, errorJson);
                logger.error("已发送错误消息到会话: {}", session.getId());
            } catch (Exception e) {
                logger.error("发送错误消息失败: {}", e.getMessage(), e);
            }
        } else {
            logger.info("会话 {} 的错误消息已发送过，跳过重复发送", sessionId);
        }
    }

    private void cancelStreamSubscription(String sessionId) {
        if (stateStore.cancelSubscription(sessionId)) {
            logger.info("已取消会话 {} 的上游流式订阅", sessionId);
        }
    }

    private void handleStreamError(WebSocketSession session,
                                   Throwable error,
                                   String conversationId,
                                   String userId,
                                   String userMessage,
                                   long requestStartNanos) {
        String sessionId = session.getId();
        ChatSessionStateStore.StreamTerminalState terminalState = stateStore.getState(sessionId);
        if (terminalState == ChatSessionStateStore.StreamTerminalState.STOPPED) {
            logger.info("会话 {} 的流式响应已被用户中止，忽略后续异常回调: {}", sessionId, error.getMessage());
            return;
        }

        stateStore.markState(sessionId, ChatSessionStateStore.StreamTerminalState.FAILED);
        handleError(session, error);
        // 持久化错误消息，以便刷新后仍可展示
        String failedMessage = (error.getMessage() != null && !error.getMessage().isEmpty())
                ? error.getMessage() : "响应处理失败";
        if (conversationId != null && userId != null && userMessage != null) {
            historyService.saveErrorMessage(conversationId, userId, userMessage, failedMessage);
        }
        // 延迟发送 completion failed，确保 error 消息先到达前端
        CompletableFuture.delayedExecutor(500, java.util.concurrent.TimeUnit.MILLISECONDS)
                .execute(() -> {
                    try {
                        if (session.isOpen()) {
                            sendCompletionNotification(session, "failed", failedMessage);
                        }
                    } catch (Exception e) {
                        logger.warn("延迟发送 completion failed 通知失败: {}", e.getMessage());
                    }
                });
        stateStore.completeFutureExceptionally(sessionId, error);
        cancelStreamSubscription(sessionId);
        stateStore.consumeResponse(sessionId);
        stateStore.clearState(sessionId);
        stateStore.clearErrorSent(sessionId);
        recordResponseTime(requestStartNanos);
        logger.warn("流式响应异常结束，会话ID: {}", sessionId, error);
    }

    private void finalizeStreamResponse(WebSocketSession session,
                                        String conversationId,
                                        String userId,
                                        String userMessage,
                                        long requestStartNanos) {
        String sessionId = session.getId();
        ChatSessionStateStore.StreamTerminalState terminalState = stateStore.getState(sessionId);
        if (terminalState == ChatSessionStateStore.StreamTerminalState.STOPPED) {
            logger.info("会话 {} 的流式响应已停止，忽略完成回调", sessionId);
            return;
        }
        if (terminalState == ChatSessionStateStore.StreamTerminalState.FAILED) {
            logger.info("会话 {} 的流式响应已失败，忽略完成回调", sessionId);
            return;
        }

        stateStore.markState(sessionId, ChatSessionStateStore.StreamTerminalState.COMPLETED);
        String completeResponse = stateStore.consumeResponse(sessionId);

        logger.info("DeepSeek响应已完成，长度: {}，会话ID: {}", completeResponse.length(), sessionId);
        cancelStreamSubscription(sessionId);
        stateStore.completeFuture(sessionId, completeResponse);
        sendCompletionNotification(session, "finished", "响应已完成");
        historyService.updateConversationHistory(conversationId, userId, userMessage, completeResponse);

        // 将对话记录持久化到 MySQL，供个人使用统计查询
        try {
            conversationService.recordConversation(userId, userMessage, completeResponse);
            logger.debug("对话已写入数据库，用户ID: {}，会话ID: {}", userId, conversationId);
        } catch (Exception e) {
            logger.warn("对话写入数据库失败（不影响主流程），用户ID: {}，原因: {}", userId, e.getMessage());
        }

        String redisKey = historyService.userCurrentConversationKey(userId);
        logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);

        stateStore.clearState(sessionId);
        stateStore.clearErrorSent(sessionId);
        recordResponseTime(requestStartNanos);
        logger.info("消息处理完成，用户ID: {}，会话ID: {}", userId, sessionId);
    }

    private void recordQuestionAnalytics(String question, boolean kbHit) {
        try {
            String day = LocalDate.now().toString();
            redisTemplate.opsForValue().increment("analytics:qa:" + day);
            redisTemplate.opsForValue().increment("analytics:kb:" + day + ":" + (kbHit ? "hit" : "miss"));
            if (hasText(question)) {
                redisTemplate.opsForZSet().incrementScore("analytics:popular_questions:" + day, question.trim(), 1);
            }
        } catch (Exception e) {
            logger.warn("记录问答分析指标失败: {}", e.getMessage());
        }
    }

    private void recordResponseTime(long requestStartNanos) {
        try {
            long elapsedMs = Math.max(0, (System.nanoTime() - requestStartNanos) / 1_000_000);
            String day = LocalDate.now().toString();
            redisTemplate.opsForValue().increment("analytics:response_time_sum:" + day, elapsedMs);
            redisTemplate.opsForValue().increment("analytics:response_time_count:" + day);
        } catch (Exception e) {
            logger.warn("记录响应时间指标失败: {}", e.getMessage());
        }
    }

    /**
     * 停止响应
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);

        ChatSessionStateStore.StreamTerminalState terminalState = stateStore.getState(sessionId);
        if (terminalState != null && terminalState != ChatSessionStateStore.StreamTerminalState.ACTIVE) {
            logger.info("会话 {} 当前终态为 {}，跳过重复停止", sessionId, terminalState);
            return;
        }

        stateStore.markState(sessionId, ChatSessionStateStore.StreamTerminalState.STOPPED);
        cancelStreamSubscription(sessionId);
        String partialResponse = stateStore.consumeResponse(sessionId);
        stateStore.completeFuture(sessionId, partialResponse);

        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = new LinkedHashMap<>();
            response.put("type", "stop");
            response.put("message", "响应已停止");
            response.put("status", "stopped");
            response.put("partialContent", partialResponse);
            response.put("timestamp", currentTime);
            response.put("date", java.time.Instant.ofEpochMilli(currentTime).toString());
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            safeSend(session, stopJson);
            sendCompletionNotification(session, "stopped", "响应已停止");
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        } finally {
            stateStore.clearState(sessionId);
        }
    }

    public void clearSessionState(String sessionId) {
        ChatSessionStateStore.ClearResult result = stateStore.clear(sessionId);

        logger.info(
                "清理会话状态完成，sessionId={}, referencesRemoved={}, responseLength={}, futureRemoved={}, terminalState={}, subscriptionRemoved={}, lockRemoved={}",
                sessionId,
                result.referencesRemoved(),
                result.responseLength(),
                result.futureRemoved(),
                result.terminalState(),
                result.subscriptionRemoved(),
                result.lockRemoved()
        );
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
