/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "ai-center_agent-management": () => import("@/views/ai-center/agent-management/index.vue"),
  "ai-center_agent-marketplace": () => import("@/views/ai-center/agent-marketplace/index.vue"),
  "ai-center_agent-workflow": () => import("@/views/ai-center/agent-workflow/index.vue"),
  "ai-center_debug-center": () => import("@/views/ai-center/debug-center/index.vue"),
  "ai-center_mcp-tools": () => import("@/views/ai-center/mcp-tools/index.vue"),
  "ai-center_model-management": () => import("@/views/ai-center/model-management/index.vue"),
  "ai-center_prompt-management": () => import("@/views/ai-center/prompt-management/index.vue"),
  "ai-center_run-analysis": () => import("@/views/ai-center/run-analysis/index.vue"),
  "ai-center_workflow": () => import("@/views/ai-center/workflow/index.vue"),
  "api-key-management": () => import("@/views/api-key-management/index.vue"),
  "ai-assistant_chat": () => import("@/views/chat/index.vue"),
  "ai-assistant_document-management": () => import("@/views/document-management/index.vue"),
  "ai-assistant_knowledge-base": () => import("@/views/knowledge-base/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "org-tag": () => import("@/views/org-tag/index.vue"),
  "permission-center_org-management": () => import("@/views/permission-center/org-management/index.vue"),
  "permission-center_role-management": () => import("@/views/permission-center/role-management/index.vue"),
  "permission-center_user-management": () => import("@/views/permission-center/user-management/index.vue"),
  "personal-center": () => import("@/views/personal-center/index.vue"),
  "system-overview": () => import("@/views/system-overview/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
