/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types'

export const generatedRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai-center',
    path: '/ai-center',
    component: 'layout.base',
    meta: {
      title: 'ai-center',
      i18nKey: 'route.ai-center',
      icon: 'carbon:ai-status',
      order: 3.5
    },
    children: [
      {
        name: 'ai-center_agent-management',
        path: '/ai-center/agent-management',
        component: 'view.ai-center_agent-management',
        meta: {
          title: 'ai-center_agent-management',
          i18nKey: 'route.ai-center_agent-management',
          icon: 'carbon:bot',
          order: 1
        }
      },
      {
        name: 'ai-center_agent-marketplace',
        path: '/ai-center/agent-marketplace',
        component: 'view.ai-center_agent-marketplace',
        meta: {
          title: 'ai-center_agent-marketplace',
          i18nKey: 'route.ai-center_agent-marketplace',
          icon: 'carbon:store',
          order: 6
        }
      },
      {
        name: 'ai-center_debug-center',
        path: '/ai-center/debug-center',
        component: 'view.ai-center_debug-center',
        meta: {
          title: 'ai-center_debug-center',
          i18nKey: 'route.ai-center_debug-center',
          icon: 'carbon:debug',
          order: 7
        }
      },
      {
        name: 'ai-center_mcp-tools',
        path: '/ai-center/mcp-tools',
        component: 'view.ai-center_mcp-tools',
        meta: {
          title: 'ai-center_mcp-tools',
          i18nKey: 'route.ai-center_mcp-tools',
          icon: 'carbon:tool-kit',
          order: 3
        }
      },
      {
        name: 'ai-center_model-management',
        path: '/ai-center/model-management',
        component: 'view.ai-center_model-management',
        meta: {
          title: 'ai-center_model-management',
          i18nKey: 'route.ai-center_model-management',
          icon: 'carbon:model',
          order: 5
        }
      },
      {
        name: 'ai-center_prompt-management',
        path: '/ai-center/prompt-management',
        component: 'view.ai-center_prompt-management',
        meta: {
          title: 'ai-center_prompt-management',
          i18nKey: 'route.ai-center_prompt-management',
          icon: 'carbon:text-annotation-toggle',
          order: 4
        }
      },
      {
        name: 'ai-center_run-analysis',
        path: '/ai-center/run-analysis',
        component: 'view.ai-center_run-analysis',
        meta: {
          title: 'ai-center_run-analysis',
          i18nKey: 'route.ai-center_run-analysis',
          icon: 'carbon:chart-line-data',
          order: 8
        }
      },
      {
        name: 'ai-center_workflow',
        path: '/ai-center/workflow',
        component: 'view.ai-center_workflow',
        meta: {
          title: 'ai-center_workflow',
          i18nKey: 'route.ai-center_workflow',
          icon: 'carbon:flow',
          order: 2
        }
      }
    ]
  },
  {
    name: 'api-key-management',
    path: '/api-key-management',
    component: 'layout.base$view.api-key-management',
    meta: {
      title: 'api-key-management',
      i18nKey: 'route.api-key-management',
      icon: 'solar:key-minimalistic-square-line-duotone',
      roles: ['ADMIN'],
      permissions: ['system:admin'],
      order: 5.5
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'org-tag',
    path: '/org-tag',
    component: 'layout.base$view.org-tag',
    meta: {
      title: 'org-tag',
      i18nKey: 'route.org-tag',
      hideInMenu: true
    }
  },
  {
    name: 'permission-center',
    path: '/permission-center',
    component: 'layout.base',
    meta: {
      title: 'permission-center',
      i18nKey: 'route.permission-center',
      icon: 'solar:shield-keyhole-line-duotone',
      roles: ['ADMIN'],
      permissions: ['system:admin'],
      order: 5
    },
    children: [
      {
        name: 'permission-center_org-management',
        path: '/permission-center/org-management',
        component: 'view.permission-center_org-management',
        meta: {
          title: 'permission-center_org-management',
          i18nKey: 'route.permission-center_org-management',
          icon: 'solar:buildings-line-duotone',
          roles: ['ADMIN'],
          permissions: ['system:admin'],
          order: 1
        }
      },
      {
        name: 'permission-center_role-management',
        path: '/permission-center/role-management',
        component: 'view.permission-center_role-management',
        meta: {
          title: 'permission-center_role-management',
          i18nKey: 'route.permission-center_role-management',
          order: 2
        }
      },
      {
        name: 'permission-center_user-management',
        path: '/permission-center/user-management',
        component: 'view.permission-center_user-management',
        meta: {
          title: 'permission-center_user-management',
          i18nKey: 'route.permission-center_user-management',
          icon: 'solar:user-line-duotone',
          roles: ['ADMIN'],
          permissions: ['user:read'],
          order: 3
        }
      }
    ]
  },
  {
    name: 'personal-center',
    path: '/personal-center',
    component: 'layout.base$view.personal-center',
    meta: {
      title: 'personal-center',
      i18nKey: 'route.personal-center',
      icon: 'solar:people-nearby-line-duotone',
      order: 6
    }
  },
  {
    name: 'system-overview',
    path: '/system-overview',
    component: 'layout.base$view.system-overview',
    meta: {
      title: 'system-overview',
      i18nKey: 'route.system-overview',
      icon: 'carbon:dashboard',
      roles: ['ADMIN'],
      permissions: ['system:admin'],
      order: 0
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      hideInMenu: true
    }
  }
];
