import { theme as antdTheme } from 'antd'
import type { ThemeConfig } from 'antd'

import type { ThemeId } from '@/stores/theme'

const sharedTokens = {
  fontFamilyCode: '"JetBrains Mono", "Fira Code", monospace',
  fontSize: 14,
  fontSizeLG: 16,
  fontSizeSM: 12,
  motionDurationFast: '0.1s',
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',
}

const enterpriseFontFamily = '"Inter", system-ui, -apple-system, sans-serif'
const earthFontFamily = '"Nunito", system-ui, -apple-system, sans-serif'
const jakartaFontFamily = '"Plus Jakarta Sans", system-ui, -apple-system, sans-serif'
const dmSansFontFamily = '"DM Sans", system-ui, -apple-system, sans-serif'
const sourceSerifFontFamily = '"Source Serif 4", Georgia, serif'
const monoFontFamily = '"JetBrains Mono", "Fira Code", monospace'

// ── Enterprise Simple (白)
const lightConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: enterpriseFontFamily,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    colorPrimary: '#0052FF',
    colorLink: '#0052FF',
    colorBgBase: '#FAFAFA',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FAFAFA',
    colorBgSpotlight: '#F1F5F9',
    colorBorder: '#E2E8F0',
    colorBorderSecondary: '#F1F5F9',
    colorText: '#0F172A',
    colorTextSecondary: '#64748B',
    colorTextTertiary: '#94A3B8',
    colorTextPlaceholder: '#94A3B8',
    boxShadow: '0 4px 6px rgba(0,0,0,0.07)',
    boxShadowSecondary: '0 1px 3px rgba(0,0,0,0.06)',
  },
  components: {
    Layout: {
      siderBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      bodyBg: '#FAFAFA',
      triggerBg: '#F1F5F9',
      triggerColor: '#64748B',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(0,82,255,0.08)',
      itemSelectedColor: '#0052FF',
      itemHoverBg: '#F1F5F9',
      itemHoverColor: '#0F172A',
      itemActiveBg: 'rgba(0,82,255,0.12)',
      itemColor: '#64748B',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(0,82,255,0.25)',
      borderRadius: 8,
      borderRadiusLG: 10,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 8, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 8, controlHeight: 36 },
    Card: { borderRadius: 12, boxShadow: '0 1px 3px rgba(0,0,0,0.06)' },
    Table: { borderRadius: 12, headerBg: '#F1F5F9', rowHoverBg: '#F8FAFF' },
    Modal: { borderRadius: 16 },
    Drawer: { borderRadius: 16 },
    Tag: { borderRadius: 4 },
    Tabs: { inkBarColor: '#0052FF', itemSelectedColor: '#0052FF', itemHoverColor: '#0047E0' },
    Tooltip: { colorBgSpotlight: '#F1F5F9', colorTextLightSolid: '#0F172A' },
  },
}

// ── Enterprise Simple (黑)
const darkConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.darkAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: enterpriseFontFamily,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    colorPrimary: '#4D7CFF',
    colorLink: '#4D7CFF',
    colorBgBase: '#0A0A0F',
    colorBgContainer: '#141420',
    colorBgElevated: '#1A1A2E',
    colorBgLayout: '#0A0A0F',
    colorBgSpotlight: '#1A1A2E',
    colorBorder: '#252540',
    colorBorderSecondary: '#1E1E35',
    colorText: '#F0F4FF',
    colorTextSecondary: '#8892AA',
    colorTextTertiary: '#5A6480',
    colorTextPlaceholder: '#5A6480',
    boxShadow: '0 4px 6px rgba(0,0,0,0.35)',
    boxShadowSecondary: '0 1px 3px rgba(0,0,0,0.3)',
  },
  components: {
    Layout: {
      siderBg: '#0F0F1A',
      headerBg: '#0A0A0F',
      bodyBg: '#0A0A0F',
      triggerBg: '#141420',
      triggerColor: '#8892AA',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(77,124,255,0.15)',
      itemSelectedColor: '#6B93FF',
      itemHoverBg: 'rgba(77,124,255,0.06)',
      itemHoverColor: '#F0F4FF',
      itemActiveBg: 'rgba(77,124,255,0.2)',
      itemColor: '#8892AA',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(77,124,255,0.3)',
      borderRadius: 8,
      borderRadiusLG: 10,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 8, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 8, controlHeight: 36 },
    Card: { borderRadius: 12, boxShadow: '0 1px 3px rgba(0,0,0,0.3)' },
    Table: { borderRadius: 12, headerBg: '#1A1A2E', rowHoverBg: '#1E1E35' },
    Modal: { borderRadius: 16 },
    Drawer: { borderRadius: 16 },
    Tag: { borderRadius: 4 },
    Tabs: { inkBarColor: '#4D7CFF', itemSelectedColor: '#4D7CFF', itemHoverColor: '#6B93FF' },
    Tooltip: { colorBgSpotlight: '#1A1A2E', colorTextLightSolid: '#F0F4FF' },
  },
}

// ── Organic Earth (有机大地风)
const earthConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: earthFontFamily,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    colorPrimary: '#4F6E35',
    colorLink: '#4F6E35',
    colorBgBase: '#F7F3EB',
    colorBgContainer: '#FFFCF3',
    colorBgElevated: '#FFFCF3',
    colorBgLayout: '#F7F3EB',
    colorBgSpotlight: '#EDE5D4',
    colorBorder: '#D4C5A8',
    colorBorderSecondary: '#E3D9C5',
    colorText: '#291A0B',
    colorTextSecondary: '#7A6248',
    colorTextTertiary: '#A8906F',
    colorTextPlaceholder: '#A8906F',
    boxShadow: '0 4px 6px rgba(80,55,20,0.09)',
    boxShadowSecondary: '0 1px 3px rgba(80,55,20,0.07)',
  },
  components: {
    Layout: {
      siderBg: '#F0E8D5',
      headerBg: '#F7F3EB',
      bodyBg: '#F7F3EB',
      triggerBg: '#EDE5D4',
      triggerColor: '#7A6248',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(79,110,53,0.1)',
      itemSelectedColor: '#3E5829',
      itemHoverBg: '#E6D9C2',
      itemHoverColor: '#291A0B',
      itemActiveBg: 'rgba(79,110,53,0.15)',
      itemColor: '#8B7154',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(79,110,53,0.25)',
      borderRadius: 8,
      borderRadiusLG: 10,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 8, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 8, controlHeight: 36 },
    Card: { borderRadius: 12, boxShadow: '0 1px 3px rgba(80,55,20,0.08)' },
    Table: { borderRadius: 12, headerBg: '#EDE5D4', rowHoverBg: '#F4EEE0' },
    Modal: { borderRadius: 16 },
    Drawer: { borderRadius: 16 },
    Tag: { borderRadius: 4 },
    Tabs: { inkBarColor: '#4F6E35', itemSelectedColor: '#4F6E35', itemHoverColor: '#3E5829' },
    Tooltip: { colorBgSpotlight: '#EDE5D4', colorTextLightSolid: '#291A0B' },
  },
}

// ── Corporate Trust (企业信任)  ·  enterprise.xml
const corporateConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: jakartaFontFamily,
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    colorPrimary: '#4F46E5',
    colorLink: '#4F46E5',
    colorBgBase: '#F8FAFC',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#F8FAFC',
    colorBgSpotlight: '#F1F5F9',
    colorBorder: '#E2E8F0',
    colorBorderSecondary: '#F1F5F9',
    colorText: '#0F172A',
    colorTextSecondary: '#64748B',
    colorTextTertiary: '#94A3B8',
    colorTextPlaceholder: '#94A3B8',
    boxShadow: '0 4px 20px -2px rgba(79,70,229,0.1)',
    boxShadowSecondary: '0 1px 3px rgba(79,70,229,0.06)',
  },
  components: {
    Layout: {
      siderBg: '#FFFFFF',
      headerBg: '#F8FAFC',
      bodyBg: '#F8FAFC',
      triggerBg: '#F1F5F9',
      triggerColor: '#64748B',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(79,70,229,0.08)',
      itemSelectedColor: '#4F46E5',
      itemHoverBg: '#F1F5F9',
      itemHoverColor: '#0F172A',
      itemActiveBg: 'rgba(79,70,229,0.12)',
      itemColor: '#64748B',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(79,70,229,0.3)',
      borderRadius: 8,
      borderRadiusLG: 10,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 8, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 8, controlHeight: 36 },
    Card: { borderRadius: 12, boxShadow: '0 4px 20px -2px rgba(79,70,229,0.1)' },
    Table: { borderRadius: 12, headerBg: '#F1F5F9', rowHoverBg: '#F8FAFF' },
    Modal: { borderRadius: 16 },
    Drawer: { borderRadius: 16 },
    Tag: { borderRadius: 4 },
    Tabs: { inkBarColor: '#4F46E5', itemSelectedColor: '#4F46E5', itemHoverColor: '#4338CA' },
    Tooltip: { colorBgSpotlight: '#F1F5F9', colorTextLightSolid: '#0F172A' },
  },
}

// ── Neumorphism (拟态浮雕)  ·  Neumorphism.xml
const neoConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: dmSansFontFamily,
    // Hyper-rounded — the neumorphic signature
    borderRadius: 16,
    borderRadiusLG: 24,
    borderRadiusSM: 12,
    borderRadiusXS: 8,
    colorPrimary: '#6C63FF',
    colorLink: '#6C63FF',
    // Monochromatic: everything is the clay
    colorBgBase: '#E0E5EC',
    colorBgContainer: '#E0E5EC',
    colorBgElevated: '#E0E5EC',
    colorBgLayout: '#E0E5EC',
    colorBgSpotlight: '#D5DBE6',
    // Transparent borders — shadows do the work
    colorBorder: 'rgba(163,177,198,0.3)',
    colorBorderSecondary: 'rgba(163,177,198,0.15)',
    colorText: '#3D4852',
    colorTextSecondary: '#6B7280',
    colorTextTertiary: '#A0AEC0',
    colorTextPlaceholder: '#A0AEC0',
    boxShadow: '9px 9px 16px rgb(163,177,198,0.6), -9px -9px 16px rgba(255,255,255,0.5)',
    boxShadowSecondary: '5px 5px 10px rgb(163,177,198,0.6), -5px -5px 10px rgba(255,255,255,0.5)',
  },
  components: {
    Layout: {
      siderBg: '#E0E5EC',
      headerBg: '#E0E5EC',
      bodyBg: '#E0E5EC',
      triggerBg: '#D5DBE6',
      triggerColor: '#6B7280',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(108,99,255,0.1)',
      itemSelectedColor: '#6C63FF',
      itemHoverBg: '#D5DBE6',
      itemHoverColor: '#3D4852',
      itemActiveBg: 'rgba(108,99,255,0.15)',
      itemColor: '#6B7280',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '9px 9px 16px rgb(163,177,198,0.6), -9px -9px 16px rgba(255,255,255,0.5)',
      borderRadius: 16,
      borderRadiusLG: 20,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
    },
    Input: { borderRadius: 16, controlHeight: 40, controlHeightLG: 48 },
    Select: { borderRadius: 16, controlHeight: 40 },
    Card: {
      borderRadius: 24,
      boxShadow: '9px 9px 16px rgb(163,177,198,0.6), -9px -9px 16px rgba(255,255,255,0.5)',
    },
    Table: { borderRadius: 24, headerBg: '#D5DBE6', rowHoverBg: '#D0D7E3' },
    Modal: { borderRadius: 32 },
    Drawer: { borderRadius: 32 },
    Tag: { borderRadius: 8 },
    Tabs: { inkBarColor: '#6C63FF', itemSelectedColor: '#6C63FF', itemHoverColor: '#5A52E8' },
    Tooltip: { colorBgSpotlight: '#D5DBE6', colorTextLightSolid: '#3D4852' },
  },
}

// ── Minimalist Monochrome (极简黑白)  ·  Monochrome.xml
const monoConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: sourceSerifFontFamily,
    // Zero radius: architectural sharp corners
    borderRadius: 0,
    borderRadiusLG: 0,
    borderRadiusSM: 0,
    borderRadiusXS: 0,
    colorPrimary: '#000000',
    colorLink: '#000000',
    colorBgBase: '#FFFFFF',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FFFFFF',
    colorBgSpotlight: '#F5F5F5',
    colorBorder: '#000000',
    colorBorderSecondary: '#E5E5E5',
    colorText: '#000000',
    colorTextSecondary: '#525252',
    colorTextTertiary: '#737373',
    colorTextPlaceholder: '#737373',
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    motionDurationFast: '0.08s',
    motionDurationMid: '0.1s',
    motionDurationSlow: '0.1s',
  },
  components: {
    Layout: {
      siderBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      bodyBg: '#FFFFFF',
      triggerBg: '#F5F5F5',
      triggerColor: '#525252',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: '#000000',
      itemSelectedColor: '#FFFFFF',
      itemHoverBg: '#F5F5F5',
      itemHoverColor: '#000000',
      itemActiveBg: '#000000',
      itemColor: '#525252',
      borderRadius: 0,
      iconSize: 16,
    },
    Button: {
      primaryShadow: 'none',
      borderRadius: 0,
      borderRadiusLG: 0,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 0, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 0, controlHeight: 36 },
    Card: { borderRadius: 0, boxShadow: 'none' },
    Table: { borderRadius: 0, headerBg: '#F5F5F5', rowHoverBg: '#F5F5F5' },
    Modal: { borderRadius: 0 },
    Drawer: { borderRadius: 0 },
    Tag: { borderRadius: 0 },
    Tabs: { inkBarColor: '#000000', itemSelectedColor: '#000000', itemHoverColor: '#333333' },
    Tooltip: { colorBgSpotlight: '#000000', colorTextLightSolid: '#FFFFFF' },
  },
}

// ── Terminal CLI (终端黑绿)  ·  Terminal.xml
const terminalConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.darkAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: monoFontFamily,
    borderRadius: 0,
    borderRadiusLG: 0,
    borderRadiusSM: 0,
    borderRadiusXS: 0,
    colorPrimary: '#33FF00',
    colorLink: '#33FF00',
    colorBgBase: '#0A0A0A',
    colorBgContainer: '#0F0F0F',
    colorBgElevated: '#141414',
    colorBgLayout: '#0A0A0A',
    colorBgSpotlight: '#141414',
    colorBorder: '#1F521F',
    colorBorderSecondary: '#143314',
    colorText: '#33FF00',
    colorTextSecondary: '#1F7A00',
    colorTextTertiary: '#155200',
    colorTextPlaceholder: '#155200',
    colorError: '#FF3333',
    colorWarning: '#FFB000',
    boxShadow: '0 0 12px rgba(51,255,0,0.25)',
    boxShadowSecondary: '0 0 6px rgba(51,255,0,0.2)',
    motionDurationFast: '0.08s',
    motionDurationMid: '0.1s',
    motionDurationSlow: '0.15s',
  },
  components: {
    Layout: {
      siderBg: '#0A0A0A',
      headerBg: '#0A0A0A',
      bodyBg: '#0A0A0A',
      triggerBg: '#141414',
      triggerColor: '#1F7A00',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(51,255,0,0.1)',
      itemSelectedColor: '#33FF00',
      itemHoverBg: '#141414',
      itemHoverColor: '#33FF00',
      itemActiveBg: 'rgba(51,255,0,0.15)',
      itemColor: '#1F7A00',
      borderRadius: 0,
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 0 12px rgba(51,255,0,0.4)',
      borderRadius: 0,
      borderRadiusLG: 0,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 0, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 0, controlHeight: 36 },
    Card: { borderRadius: 0, boxShadow: '0 0 12px rgba(51,255,0,0.25)' },
    Table: { borderRadius: 0, headerBg: '#141414', rowHoverBg: '#141414' },
    Modal: { borderRadius: 0 },
    Drawer: { borderRadius: 0 },
    Tag: { borderRadius: 0 },
    Tabs: { inkBarColor: '#33FF00', itemSelectedColor: '#33FF00', itemHoverColor: '#52FF2A' },
    Tooltip: { colorBgSpotlight: '#141414', colorTextLightSolid: '#33FF00' },
  },
}

const nunitoFontFamily = '"Nunito", system-ui, -apple-system, sans-serif'
const shareMonoFontFamily = '"Share Tech Mono", monospace'
const ibmMonoFontFamily = '"IBM Plex Mono", "JetBrains Mono", monospace'

// ── Organic / Natural (自然有机)  ·  Organic.xml
const organicConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: nunitoFontFamily,
    borderRadius: 16,
    borderRadiusLG: 24,
    borderRadiusSM: 10,
    borderRadiusXS: 8,
    colorPrimary: '#5D7052',
    colorLink: '#5D7052',
    colorBgBase: '#FDFCF8',
    colorBgContainer: '#FEFEFA',
    colorBgElevated: '#FEFEFA',
    colorBgLayout: '#FDFCF8',
    colorBgSpotlight: '#F0EBE5',
    colorBorder: '#DED8CF',
    colorBorderSecondary: '#E6DCCD',
    colorText: '#2C2C24',
    colorTextSecondary: '#78786C',
    colorTextTertiary: '#9A9A8C',
    colorTextPlaceholder: '#9A9A8C',
    boxShadow: '0 4px 20px -2px rgba(93,112,82,0.12)',
    boxShadowSecondary: '0 1px 3px rgba(93,112,82,0.08)',
    motionDurationFast: '0.2s',
    motionDurationMid: '0.3s',
    motionDurationSlow: '0.5s',
  },
  components: {
    Layout: {
      siderBg: '#F5F0EA',
      headerBg: '#FDFCF8',
      bodyBg: '#FDFCF8',
      triggerBg: '#EDE5D8',
      triggerColor: '#78786C',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(93,112,82,0.1)',
      itemSelectedColor: '#4D5E43',
      itemHoverBg: '#EDE5D8',
      itemHoverColor: '#2C2C24',
      itemActiveBg: 'rgba(93,112,82,0.15)',
      itemColor: '#78786C',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(93,112,82,0.25)',
      borderRadius: 16,
      borderRadiusLG: 20,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
    },
    Input: { borderRadius: 16, controlHeight: 40, controlHeightLG: 48 },
    Select: { borderRadius: 16, controlHeight: 40 },
    Card: { borderRadius: 24, boxShadow: '0 4px 20px -2px rgba(93,112,82,0.12)' },
    Table: { borderRadius: 16, headerBg: '#F0EBE5', rowHoverBg: '#F5F0EA' },
    Modal: { borderRadius: 32 },
    Drawer: { borderRadius: 32 },
    Tag: { borderRadius: 8 },
    Tabs: { inkBarColor: '#5D7052', itemSelectedColor: '#5D7052', itemHoverColor: '#4D5E43' },
    Tooltip: { colorBgSpotlight: '#F0EBE5', colorTextLightSolid: '#2C2C24' },
  },
}

// ── Vaporwave / Outrun (蒸汽波霓虹)  ·  Vaporwave.xml  [DARK]
const vaporwaveConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.darkAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: shareMonoFontFamily,
    fontFamilyCode: shareMonoFontFamily,
    borderRadius: 0,
    borderRadiusLG: 0,
    borderRadiusSM: 0,
    borderRadiusXS: 0,
    colorPrimary: '#FF00FF',
    colorLink: '#00FFFF',
    colorBgBase: '#090014',
    colorBgContainer: '#1A103C',
    colorBgElevated: '#1E1047',
    colorBgLayout: '#090014',
    colorBgSpotlight: '#12082A',
    colorBorder: '#2D1B4E',
    colorBorderSecondary: '#2D1B4E',
    colorText: '#E0E0E0',
    colorTextSecondary: '#A090CC',
    colorTextTertiary: '#604A8A',
    colorTextPlaceholder: '#604A8A',
    colorError: '#FF00FF',
    colorWarning: '#FF9900',
    boxShadow: '0 0 15px rgba(255,0,255,0.3)',
    boxShadowSecondary: '0 0 8px rgba(255,0,255,0.2)',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
  },
  components: {
    Layout: {
      siderBg: '#0D0020',
      headerBg: '#090014',
      bodyBg: '#090014',
      triggerBg: '#12082A',
      triggerColor: '#A090CC',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(255,0,255,0.15)',
      itemSelectedColor: '#FF00FF',
      itemHoverBg: 'rgba(255,0,255,0.06)',
      itemHoverColor: '#E0E0E0',
      itemActiveBg: 'rgba(255,0,255,0.2)',
      itemColor: '#A090CC',
      borderRadius: 0,
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 0 20px #FF00FF',
      borderRadius: 0,
      borderRadiusLG: 0,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 0, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 0, controlHeight: 36 },
    Card: { borderRadius: 0, boxShadow: '0 0 15px rgba(255,0,255,0.3)' },
    Table: { borderRadius: 0, headerBg: '#12082A', rowHoverBg: '#1E1047' },
    Modal: { borderRadius: 0 },
    Drawer: { borderRadius: 0 },
    Tag: { borderRadius: 0 },
    Tabs: { inkBarColor: '#FF00FF', itemSelectedColor: '#FF00FF', itemHoverColor: '#00FFFF' },
    Tooltip: { colorBgSpotlight: '#1A103C', colorTextLightSolid: '#E0E0E0' },
  },
}

// ── Professional / Editorial Serif (典雅衬线)  ·  Professional.xml
const professionalConfig: ThemeConfig = {
  cssVar: { prefix: 'ant' },
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...sharedTokens,
    fontFamily: sourceSerifFontFamily,
    fontFamilyCode: ibmMonoFontFamily,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    borderRadiusXS: 2,
    colorPrimary: '#B8860B',
    colorLink: '#B8860B',
    colorBgBase: '#FAFAF8',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FAFAF8',
    colorBgSpotlight: '#F5F3F0',
    colorBorder: '#E8E4DF',
    colorBorderSecondary: '#EDEAE6',
    colorText: '#1A1A1A',
    colorTextSecondary: '#6B6B6B',
    colorTextTertiary: '#9A9A9A',
    colorTextPlaceholder: '#9A9A9A',
    boxShadow: '0 4px 12px rgba(26,26,26,0.06)',
    boxShadowSecondary: '0 1px 2px rgba(26,26,26,0.04)',
  },
  components: {
    Layout: {
      siderBg: '#F5F3F0',
      headerBg: '#FAFAF8',
      bodyBg: '#FAFAF8',
      triggerBg: '#EDEAE6',
      triggerColor: '#6B6B6B',
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemSelectedBg: 'rgba(184,134,11,0.08)',
      itemSelectedColor: '#B8860B',
      itemHoverBg: '#EDEAE6',
      itemHoverColor: '#1A1A1A',
      itemActiveBg: 'rgba(184,134,11,0.12)',
      itemColor: '#6B6B6B',
      iconSize: 16,
    },
    Button: {
      primaryShadow: '0 4px 14px rgba(184,134,11,0.2)',
      borderRadius: 6,
      borderRadiusLG: 8,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
    },
    Input: { borderRadius: 6, controlHeight: 36, controlHeightLG: 44 },
    Select: { borderRadius: 6, controlHeight: 36 },
    Card: { borderRadius: 8, boxShadow: '0 4px 12px rgba(26,26,26,0.06)' },
    Table: { borderRadius: 8, headerBg: '#F5F3F0', rowHoverBg: '#FAFAF8' },
    Modal: { borderRadius: 10 },
    Drawer: { borderRadius: 10 },
    Tag: { borderRadius: 2 },
    Tabs: { inkBarColor: '#B8860B', itemSelectedColor: '#B8860B', itemHoverColor: '#9A7009' },
    Tooltip: { colorBgSpotlight: '#F5F3F0', colorTextLightSolid: '#1A1A1A' },
  },
}

const THEME_CONFIGS: Record<ThemeId, ThemeConfig> = {
  light: lightConfig,
  dark: darkConfig,
  earth: earthConfig,
  corporate: corporateConfig,
  neo: neoConfig,
  mono: monoConfig,
  terminal: terminalConfig,
  organic: organicConfig,
  vaporwave: vaporwaveConfig,
  professional: professionalConfig,
}

export const getAntdTheme = (themeId: ThemeId): ThemeConfig => THEME_CONFIGS[themeId]
